package drillpad.gui;

import javax.swing.plaf.basic.BasicComboBoxRenderer;

import drillpad.domain.SceneController;
import drillpad.domain.entity.Player;

/**
 *
 * @author Eric Perron
 */
public class PlayerPropertyWindow extends javax.swing.JDialog
{
    private final SceneController controller = SceneController.getInstance();
    private final Player player;

    /**
     *
     * @param player
     */
    PlayerPropertyWindow(Player player)
    {
        this.player = player;

        initComponents();
        init();
    }

    private void init()
    {
        initComboBoxes();

        showPlayerRoleCheckBox.setSelected(player.isRoleVisible());
        showPlayerNameCheckBox.setSelected(player.isNameVisible());

        String playerName = player.getName();
        if (playerName != null &&
            !playerName.isEmpty())
        {
            playerNameTextField.setText(playerName);
        }

        playerNameTextField.requestFocusInWindow();

        setPreferredSize(null);
        setSize(getPreferredSize());
    }

    private void initComboBoxes()
    {
        for (String role : controller.getRoleNames())
        {
            roleComboBox.addItem(role);
        }
        roleComboBox.setSelectedItem(player.getRoleName());

        for (String entityType : controller.getEntityTypeNames())
        {
            if (controller.isEntityTypeTeam(entityType))
            {
                teamComboBox.addItem(entityType);
            }
        }
        teamComboBox.setSelectedItem(player.getTeamName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        roleLabel = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        teamLabel = new javax.swing.JLabel();
        teamComboBox = new javax.swing.JComboBox<>();
        playerNameLabel = new javax.swing.JLabel();
        playerNameTextField = new javax.swing.JTextField();
        showPlayerNameCheckBox = new javax.swing.JCheckBox();
        showPlayerRoleCheckBox = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Édition de joueur");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        roleLabel.setText("Rôle du joueur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 2, 5);
        getContentPane().add(roleLabel, gridBagConstraints);

        roleComboBox.setMaximumSize(new java.awt.Dimension(140, 24));
        roleComboBox.setMinimumSize(new java.awt.Dimension(140, 24));
        roleComboBox.setPreferredSize(new java.awt.Dimension(140, 24));
        roleComboBox.setRenderer(new BasicComboBoxRenderer());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 5, 5);
        getContentPane().add(roleComboBox, gridBagConstraints);

        teamLabel.setText("Équipe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 2, 5);
        getContentPane().add(teamLabel, gridBagConstraints);

        teamComboBox.setMaximumSize(new java.awt.Dimension(140, 24));
        teamComboBox.setMinimumSize(new java.awt.Dimension(140, 24));
        teamComboBox.setPreferredSize(new java.awt.Dimension(140, 24));
        teamComboBox.setRenderer(new BasicComboBoxRenderer());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 5, 5);
        getContentPane().add(teamComboBox, gridBagConstraints);

        playerNameLabel.setText("Nom du joueur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 2, 5);
        getContentPane().add(playerNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 5, 5);
        getContentPane().add(playerNameTextField, gridBagConstraints);

        showPlayerNameCheckBox.setText("Afficher nom du joueur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(showPlayerNameCheckBox, gridBagConstraints);

        showPlayerRoleCheckBox.setText("Afficher rôle du joueur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(showPlayerRoleCheckBox, gridBagConstraints);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(90, 23));
        okButton.setMinimumSize(new java.awt.Dimension(90, 23));
        okButton.setPreferredSize(new java.awt.Dimension(90, 23));
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        getContentPane().add(okButton, gridBagConstraints);

        cancelButton.setText("Annuler");
        cancelButton.setMaximumSize(new java.awt.Dimension(90, 23));
        cancelButton.setMinimumSize(new java.awt.Dimension(90, 23));
        cancelButton.setPreferredSize(new java.awt.Dimension(90, 23));
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        getContentPane().add(cancelButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        String newTeamName = teamComboBox.getSelectedItem().toString();
        String newRoleName = roleComboBox.getSelectedItem().toString();
        String newPlayerName = playerNameTextField.getText();
        boolean newIsRoleVisible = showPlayerRoleCheckBox.isSelected();
        boolean newIsNameVisible = showPlayerNameCheckBox.isSelected();

        // TODO(Eric): Add validations like the other propertyWindow
        controller.editPlayer(player, newTeamName, newRoleName, newPlayerName,
                              newIsRoleVisible, newIsNameVisible);

        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JTextField playerNameTextField;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JCheckBox showPlayerNameCheckBox;
    private javax.swing.JCheckBox showPlayerRoleCheckBox;
    private javax.swing.JComboBox<String> teamComboBox;
    private javax.swing.JLabel teamLabel;
    // End of variables declaration//GEN-END:variables
}
// TODO(Eric): add menuItem in "Éditer" (enable/disable when required)
